### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ronsala** [kahlil/belly#7]
I just installed belly on a Macbook Pro running Mojave. When I run 'belly c' or 'belly --help' I get:

/Users/RonSala/.nvm/versions/node/v6.11.2/lib/node_modules/belly/lib/belly.js:9
module.exports = async cli => {
                       ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/RonSala/.nvm/versions/node/v6.11.2/lib/node_modules/belly/cli.js:5:15)

**Comment by khalillechelt** [comment]
I'll check it out thanks

**Comment by khalillechelt** [comment]
Hi, it works for me but I am using the latest LTS version of Node. Which version are you using?
I will have to update the Node version requirement.

**Comment by khalillechelt** [comment]
Just pushed a new patch version that requires Node v10 or larger.

**Comment by ronsala** [comment]
I just tried again after updating to Node.js v10.16.3. Everything seems to be working fine now.
